# Generated by Django 6.0.3 on 2026-05-01 01:51

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0005_convocatoria_archivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('error_procesamiento', 'Error de Procesamiento')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('archivo', models.TextField(help_text='Archivo del documento (PDF o imagen)', max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'tiff', 'bmp'])])),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('error_procesamiento', 'Error de Procesamiento')], default='pendiente', max_length=20)),
                ('estado_semaforo', models.CharField(choices=[('verde', '🟢 Válido'), ('amarillo', '🟡 Requiere revisión'), ('rojo', '🔴 Inválido')], default='amarillo', max_length=10)),
                ('texto_extraido', models.TextField(blank=True, null=True)),
                ('confianza_ocr', models.IntegerField(default=0, help_text='Confianza OCR de 0 a 100')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tipo_validacion', models.CharField(choices=[('automatica', 'Automática'), ('manual', 'Manual')], default='automatica', max_length=20)),
                ('numero_documento_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_carga', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('convocatoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documental.convocatoria')),
                ('documento_requerido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documental.documentorequerido')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('postulante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documental.postulante')),
            ],
            options={
                'verbose_name': 'historical Documento',
                'verbose_name_plural': 'historical Documentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExpediente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('en_proceso', 'En Proceso')], default='en_proceso', max_length=20)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('convocatoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documental.convocatoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('postulante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documental.postulante')),
            ],
            options={
                'verbose_name': 'historical Expediente',
                'verbose_name_plural': 'historical Expedientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
